#!/bin/sh
set -e
if [ "$1" = "install" ] || [ "$1" = "upgrade" ]; then
    dpkg-divert --add --package adaptation-star2qltechn-configs --rename \
        --divert /usr/bin/usb-tethering.hybris /usr/bin/usb-tethering
fi
